select * from customer;
-- Q1.What is the total revenue generated by male vs female customers ?
-- select gender,sum(purchase_amount) as revenue
-- from customer 
-- group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
-- select customer_id,purchase_amount 
-- from customer
-- where discount_applied ='Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?
-- select item_purchased , round(avg(review_rating::numeric),2) as average_review_rating
-- from customer
-- group by item_purchased
-- order by average_review_rating desc
-- limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
-- select shipping_type,round(avg(purchase_amount),2) as average_purchase_type
-- from customer
-- -- where shipping_type in ('Express','Standard')
-- group by shipping_type
-- having shipping_type in ('Express','Standard');

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
-- select count(customer_id) as customer_count,subscription_status,avg(purchase_amount) as avg_spend, sum(purchase_amount) as total_revenue
-- from customer
-- group by subscription_status
-- order by avg_spend,total_revenue desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

--Q8. What are the top 3 most purchased products within each category? 
select item_purchased as product,

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
-- select subscription_status,count(customer_id) as repeated_buyers
-- from customer
-- where previous_purchases >5
-- group by subscription_status;

--Q10. What is the revenue contribution of each age group? 
-- select age_group,sum(purchase_amount) as revenue
-- from customer
-- group by age_group
-- order by revenue desc;